import { Blocks, Database, GitBranch, Gauge, Layers3, ShieldCheck, Workflow, Zap } from 'lucide-react';
import type { ExpertiseGroup } from '@/types';

/** Technical depth map rendered as an interactive grid in the Expertise section. */
export const EXPERTISE_GROUPS: ExpertiseGroup[] = [
  {
    id: 'architecture',
    title: 'System Design & Architecture',
    icon: Blocks,
    gradient: 'from-blue-500 to-cyan-400',
    topics: [
      'System Design',
      'Microservices',
      'Scalable Architecture',
      'Event-Driven Systems',
      'API Gateway',
      'Service Discovery',
      'Circuit Breakers',
    ],
  },
  {
    id: 'apis',
    title: 'APIs & Integration',
    icon: Workflow,
    gradient: 'from-purple-500 to-fuchsia-400',
    topics: [
      'REST API Design',
      'Feign Clients',
      'Webhooks',
      'Apache Kafka',
      'ActiveMQ',
      'Third-Party Integrations',
      'Idempotency',
    ],
  },
  {
    id: 'data',
    title: 'Data & Performance',
    icon: Database,
    gradient: 'from-emerald-400 to-teal-500',
    topics: [
      'Database Optimization',
      'Query Tuning',
      'Indexing',
      'Partitioning',
      'Read Replicas',
      'Redis Caching',
      'Connection Pooling',
    ],
  },
  {
    id: 'security',
    title: 'Security',
    icon: ShieldCheck,
    gradient: 'from-rose-500 to-pink-400',
    topics: [
      'Authentication',
      'Authorization',
      'JWT',
      'OAuth 2.0',
      'Spring Security',
      'Role-Based Access Control',
      'Input Validation',
    ],
  },
  {
    id: 'delivery',
    title: 'CI/CD & Delivery',
    icon: GitBranch,
    gradient: 'from-amber-400 to-orange-500',
    topics: [
      'CI/CD Pipelines',
      'Jenkins',
      'GitLab CI',
      'GitHub Actions',
      'Docker',
      'Maven',
      'Release Automation',
    ],
  },
  {
    id: 'engineering',
    title: 'Engineering Practices',
    icon: Layers3,
    gradient: 'from-indigo-500 to-blue-400',
    topics: [
      'Design Patterns',
      'SOLID Principles',
      'Clean Architecture',
      'MVC',
      'Code Reviews',
      'Technical Documentation',
      'Test-Driven Development',
    ],
  },
  {
    id: 'jvm',
    title: 'JVM Internals',
    icon: Zap,
    gradient: 'from-cyan-400 to-blue-500',
    topics: [
      'Multithreading',
      'Concurrency',
      'Exception Handling',
      'Collections Framework',
      'Streams API',
      'Memory Management',
      'Garbage Collection',
    ],
  },
  {
    id: 'performance',
    title: 'Performance Engineering',
    icon: Gauge,
    gradient: 'from-violet-500 to-purple-500',
    topics: [
      'Performance Optimization',
      'Caching Strategy',
      'Low-Latency Design',
      'Async Processing',
      'Batch Processing',
      'Load Handling',
      'Profiling & Debugging',
    ],
  },
];
